### ISSUE TITLE
How to mimic gulp-twig base behaviour?

### ISSUE THREAD

**Issue by dnnsjsk** [ericmorand/gulp-twing#28] opened 2021-08-05 14:35 UTC
Hey,

I want to try out Twing (using twig.js atm) for my build pipeline, however, I can't seem to replicate the base behaviour. I am loading all of my templates from a base folder, so all extends, embed paths etc. are relative to this folder.

This is how I use twig-gulp atm:
```js
const twig = require("gulp-twig");

.pipe(
  twig({
    base: "src/twig",
    data: {
      baseType: type,
    },
  })
)
```

I've tried this (and various other variations) but it's not working.
```js
const twig = require("gulp-twing");

const { TwingEnvironment, TwingLoaderFilesystem } = require("twing");
const env = new TwingEnvironment(new TwingLoaderFilesystem(__dirname + '/src/twig/'));

.pipe(
  twig(
    env,
    {
      baseType: type,
    }
  )
)
```

**Comment by ericmorand** [comment] 2021-08-05 16:05
Hi @dnnsjsk ,

In theory, and except if I'm missing something obvious, what you did is correct. What error message do you receive?

**Comment by dnnsjsk** [comment] 2021-08-05 21:49
Hey @ericmorand,
this is the error:

[23:47:22] TwingErrorLoader: Unable to find template "src/twig/glaze/blocks_screen/home/end.twig" (looked into: /Users/dennis/Local Sites/fabrikat/app/public/wp-content/plugins/fabrikat/src/twig).
    at /Users/dennis/Local Sites/fabrikat/app/public/wp-content/plugins/fabrikat/node_modules/twing/dist/cjs/lib/loader/filesystem.js:209:39
    at async Promise.all (index 0)

**Comment by ericmorand** [comment] 2021-08-06 07:30
It is as if Twing is trying to resolve the template named `src/twig/glaze/blocks_screen/home/end.twig` instead of the template named `glaze/blocks_screen/home/end.twig`.

Before I start investigating the plugin can you make sure that you actually include `glaze/blocks_screen/home/end.twig`?

**Comment by dnnsjsk** [comment] 2021-08-06 08:19
What do you mean by that @ericmorand? The file definitely exists and is being picked up correctly by gulp-twig.

Edit: I can invite you to the repo if this can help!

**Comment by ericmorand** [comment] 2021-08-06 08:37
It would definitely help, thank you :)

**Comment by dnnsjsk** [comment] 2021-08-06 09:12
Invite is out, thanks for looking into it!

**Comment by ericmorand** [comment] 2021-08-06 13:36
Thanks @dnnsjsk 

I think I found the issue. Gulp `src` resolves files from the working directory, hence pass to `gulp-twing` some `./src/twig/...` template names. These names can't be resolved by your loader since its entry point is `./src/twig` and it tries to resolve the file `./src/twig/src/twig/...`.

This is the expected behavior of TwingLoaderFilesystem.

To solve this, you could be tempted to use `.` as the TwingLoaderFilesystem entry point instead of `./src/twig` but it would render your `{% includes %}` and `{% extends %}` invalid.

Fortunately, we have a chain loader for that:

```js
  const { TwingEnvironment, TwingLoaderFilesystem, TwingLoaderChain } = require("twing");
  const env = new TwingEnvironment(
    new TwingLoaderChain([
      new TwingLoaderFilesystem(__dirname + '/src/twig/'), // will resolve the {% include %} / {% extends %} tags
      new TwingLoaderFilesystem(__dirname) // will resolve the entry points resolved by gulp
    ])
  );
```

This loader will attempt to resolve templates using its children loaders, in the order where there have been declared, and will only fail if none of them returns a template.

Twig.js on the other hand always try to resolve things from the working directory _and_ the `base` passed as config. That's why it worked.

**Comment by dnnsjsk** [comment] 2021-08-06 16:34
@ericmorand 

You are an absolute legend! It works. :-)
Now onto fixing what twig.js thought was correct Twig.

Another unrelated question while this is open:
I am using Twig with WordPress and making use of the ```fn()``` Twig function there. To prevent Twig.js errors, I was making use of this conditional:
```js
{% if prod is defined %}
  {{ fn('wp_footer') }}
{% else %}
```

However, Twing seems to still try and get into those blocks although **prod** is not defined and I am getting ```Unknown "fn" function``` errors. To fix this issue I just registered a dummy function using this code:
```js
  const componentFunction = new TwingFunction(
    "fn",
    function (env) {
      return env;
    },
    []
  );

  env.addFunction(componentFunction);
```

That seems a bit hacky though, do you have other suggestions?

**Comment by ericmorand** [comment] 2021-08-06 16:58
You are right, Twing will fail to compile the template if the `fn` function is not registered.

It is because Twing begins by parsing the template - i.e. check that the syntax is valid. `fn` not being part of the language specification, it is an invalid syntax, _except_ if it's registered as valid in the environment, just like you did by using `addFunction`.

This is analoguous to this code that would not compile in TypeScript for example:

```ts
if (prod) {
    nonDeclaredFunction(); // error TS2304: Cannot find name 'nonDeclaredFunction'.
}
```

So, your approach is not only _not_ hacky, it _is_ the correct and the only one available to add some semantic to Twig syntax. Twing is much more reliable than twig.js and that was one of the reason I wrote it. twig.js is an amazing product and a lot of people prefer its loose approach to the stubborn one of Twing. :)

Out of curiosuty, what is the `fn` function supposed to do?

**Comment by dnnsjsk** [comment] 2021-08-06 17:22
Awesome, that's good to hear. The ```fn()``` function allows calling PHP functions when using Timber. (https://github.com/timber/timber)

While we are at it, I got another one that I can't figure out:

home.twig
```twig
{% extends 'spx/base.twig' %}

{% block content %}
  {% include 'spx/pages/_home.twig' %}
{% endblock %}
```

Is giving me the following error:
```
[19:20:07] 'createPages' errored after 1.22 s
[19:20:07] TypeError: e.getTemplateLine is not a function
    at /Users/dennis/Local Sites/fabrikat/app/public/wp-content/plugins/fabrikat/node_modules/twing/dist/cjs/lib/callable-wrapper.js:47:23
    at async Object.doDisplay (eval at getTemplatesModule (/Users/dennis/Local Sites/fabrikat/app/public/wp-content/plugins/fabrikat/node_modules/twing/dist/cjs/lib/environment.js:489:24), <anonymous>:41:801)
    at async Object.doDisplay (eval at getTemplatesModule (/Users/dennis/Local Sites/fabrikat/app/public/wp-content/plugins/fabrikat/node_modules/twing/dist/cjs/lib/environment.js:489:24), <anonymous>:61:17)
    at async Object.doDisplay (eval at getTemplatesModule (/Users/dennis/Local Sites/fabrikat/app/public/wp-content/plugins/fabrikat/node_modules/twing/dist/cjs/lib/environment.js:489:24), <anonymous>:21:35)
    at async Object.doDisplay (eval at getTemplatesModule (/Users/dennis/Local Sites/fabrikat/app/public/wp-content/plugins/fabrikat/node_modules/twing/dist/cjs/lib/environment.js:489:24), <anonymous>:437:35)
```

However, if I copy the content of ```_home.twig``` into the content block, it works without problems.

**Comment by ericmorand** [comment] 2021-08-06 21:02
Well, this is actually a bug in Twing with the `replace` filter, when the filtered value is undefined. I'll fix it. The error occurs in:

`src/twig/glaze/_primitives/container.twig` at line 21.

https://gitlab.com/nightlycommit/twing/-/issues/536

**Closed as completed by ericmorand** 2021-08-06 21:02 UTC
Labels: question
